Added 'Rocket League' command
YorkAARGH/Okami pull request #43
Opened 2018-02-08 22:38 UTC by YoussefElshemi

Get's the stats of players, works on all platforms

2018-02-08 23:03 UTC, AndrewJWin commented
Proof?

2018-02-09 01:45 UTC, MrJacz commented
I don't recommend the use of Rocket league stats, their API is heavily rate limited

2018-02-09 01:54 UTC, MrJacz requested changes

2018-02-09 01:54 UTC, MrJacz commented on commands/games/rocket.js
> +        if (!args[0] || !args[1]) return message.response("❗", `Invalid Usage, please do:\`${this.help.usage}\``);
use `!args.length`

2018-02-09 01:54 UTC, MrJacz commented on commands/games/rocket.js
> +            rocket.getPlayer(args.splice(1).join(" "), platform).then(player => {
Use async/await

2018-02-09 01:54 UTC, MrJacz commented on commands/games/rocket.js
> +                if(player.avatar) embed.setThumbnail(player.avatar)
Add this before `message.channel.send(embed)`

2018-02-09 01:54 UTC, MrJacz commented on commands/games/rocket.js
> +                message.channel.send(embed)
Missing semi colon

2018-02-09 01:54 UTC, MrJacz commented on commands/games/rocket.js
> +                embed.setColor(message.guild.member(client.user.id).roles.highest.color || 0x00AE86);
use `message.guild.me`

2018-02-09 10:52 UTC, YoussefElshemi commented on commands/games/rocket.js
> +        if (!args[0] || !args[1]) return message.response("❗", `Invalid Usage, please do:\`${this.help.usage}\``);
done all 👍

2018-02-09 10:53 UTC, YoussefElshemi commented
https://youssef.hacked-your.webcam/fxjEzRKYn.png
proof

2018-02-09 10:54 UTC, MrJacz requested changes

2018-02-09 10:54 UTC, MrJacz commented on commands/games/rocket.js
> +            await rocket.getPlayer(args.splice(1).join(" "), platform).then((player) => {
This is not how you use async/await...

2018-02-09 10:56 UTC, MrJacz commented on commands/games/rocket.js
> +            usage: "rocket [pc/xbl/psn] [username]",
also use `|` not `/`

2018-02-09 11:01 UTC, MrJacz commented on commands/games/rocket.js
> +        if (!args[0].length || !args[1].length) return message.response("❗", `Invalid Usage, please do:\`${this.help.usage}\``);
this is not what I meant either

2018-02-09 11:05 UTC, MrJacz commented on commands/games/rocket.js
> +            const player = await rocket.getPlayer(args.splice(1).join(" "), platform)
Missing semi

2018-02-09 11:06 UTC, MrJacz requested changes

2018-02-09 11:06 UTC, MrJacz commented on commands/games/rocket.js
> +                .setColor(message.guild.me.roles.highest.color || 0x00AE86)
Missing semi

2018-02-12 19:29 UTC, YorkAARGH commented on commands/games/rocket.js
> +            usage: "rocket [pc|xbl|psn] [username]",
Can you change these to required? `<pc|xb1|psn> <username>`

2018-02-12 19:32 UTC, YorkAARGH commented on commands/games/rocket.js
> +            message.response("❗", `Player not found or Invalid Usage, please do:\`${this.help.usage}\``);
Could you also console log the error as well, using the client logger.

2018-02-14 02:35 UTC, AndrewJWin requested changes
```
  3:47  error  Missing semicolon                              semi
   7:1   error  Expected indentation of 2 spaces but found 4   indent
   8:1   error  Expected indentation of 4 spaces but found 8   indent
   9:1   error  Expected indentation of 6 spaces but found 12  indent
  10:1   error  Expected indentation of 6 spaces but found 12  indent
  11:1   error  Expected indentation of 6 spaces but found 12  indent
  12:1   error  Expected indentation of 6 spaces but found 12  indent
  13:1   error  Expected indentation of 6 spaces but found 12  indent
  14:1   error  Expected indentation of 6 spaces but found 12  indent
  15:1   error  Expected indentation of 4 spaces but found 8   indent
  16:1   error  Expected indentation of 2 spaces but found 4   indent
  16:6   error  Unnecessary semicolon                          no-extra-semi
  18:1   error  Expected indentation of 2 spaces but found 4   indent
  18:30  error  'level' is defined but never used              no-unused-vars
  19:1   error  Expected indentation of 4 spaces but found 8   indent
  20:1   error  Expected indentation of 4 spaces but found 8   indent
  20:54  error  'platform' is not defined                      no-undef
  21:1   error  Expected indentation of 4 spaces but found 8   indent
  21:53  error  'platform' is not defined                      no-undef
  22:1   error  Expected indentation of 4 spaces but found 8   indent
  22:54  error  'platform' is not defined                      no-undef
  24:1   error  Expected indentation of 4 spaces but found 8   indent
  25:1   error  Expected indentation of 6 spaces but found 12  indent
  25:77  error  'platform' is not defined                      no-undef
  26:1   error  Expected indentation of 6 spaces but found 16  indent
  27:1   error  Expected indentation of 8 spaces but found 16  indent
  28:1   error  Expected indentation of 8 spaces but found 16  indent
  29:1   error  Expected indentation of 8 spaces but found 16  indent
  30:1   error  Expected indentation of 8 spaces but found 16  indent
  31:1   error  Expected indentation of 8 spaces but found 16  indent
  32:1   error  Expected indentation of 8 spaces but found 16  indent
  33:1   error  Expected indentation of 8 spaces but found 16  indent
  34:1   error  Expected indentation of 8 spaces but found 16  indent
  35:1   error  Expected indentation of 8 spaces but found 16  indent
  36:1   error  Expected indentation of 8 spaces but found 16  indent
  37:1   error  Expected indentation of 6 spaces but found 16  indent
  37:17  error  Expected space(s) after "if"                   keyword-spacing
  38:1   error  Expected indentation of 6 spaces but found 16  indent
  39:1   error  Expected indentation of 4 spaces but found 8   indent
  40:1   error  Expected indentation of 6 spaces but found 12  indent
  40:44  error  Missing semicolon                              semi
  41:1   error  Expected indentation of 6 spaces but found 12  indent
  42:1   error  Expected indentation of 4 spaces but found 8   indent
  42:10  error  Unnecessary semicolon                          no-extra-semi
  43:1   error  Expected indentation of 2 spaces but found 4   indent
  43:6   error  Unnecessary semicolon                          no-extra-semi
  44:2   error  Unnecessary semicolon                          no-extra-semi
```
Travis absolutely puked over this..

2018-02-16 20:47 UTC, YorkAARGH commented
Closing this until you fix the eslint errors.

2018-02-16 20:47 UTC, closed without merging